### ISSUE TITLE
Headless test driver performance

### ISSUE THREAD

**Issue by tonywok** [rwz/ember-cli-rails#71] opened 2015-01-27 17:42 UTC
The application I'm working on drives the ember application with capybara-webkit, and in some cases, selenium.

I've noticed that the same tests run dramatically slower when using capybara-webkit instead of selenium. For example, the selenium run takes 14 seconds, whereas the same test run with capybara-webkit takes 1 minute and 24 seconds. Aside from being headless vs not headless, I'm not sure what differences might cause this.

I realize this isn't the most helpful "issue" report as I haven't yet identified the problem. Currently looking into the ember-cli-rails internals for something that could be causing this. The gem README mentions "frameworks like cucumber" -- out of curiosity, what test drivers have you tried? Have you noticed anything similar to this report? If so, are there any good debug hooks I can use to get some visibility into what's happening during the build? (e.g maybe it's kicking off builds or getting stuck)

Appreciate any insight, and I'll post any extra information I find.

**Comment by pedrocarrico** [comment] 2015-01-27 17:50
@tonywok I'm currently using cucumber with poltergeist and I've been migrating an "old" ember application to an ember-cli application using ember-cli-rails and I didn't notice any performance drop, test integration with cucumber was seamless between the backend and frontend apps.

**Comment by pedrocarrico** [comment] 2015-01-27 17:51
@tonywok BTW, be sure to check your Guardfile and see if you're not including any unnecessary directories.

**Comment by tonywok** [comment] 2015-01-27 18:15
@pedrocarrico Not using guard. I'll try poltergeist to see if the problem is capybara-webkit specific.

**Comment by rondale-sc** [comment] 2015-01-27 18:28
@tonywok Please keep us updated on this.  I don't know of any driver specific concerns with ember-cli-rails but it'd be interesting if you found something.  :)

**Comment by tonywok** [comment] 2015-01-27 19:46
Okay, so I configured the `:poltergeist` driver and noticed speeds similar to what I had reported with `:selenium`.

After looking at our test setup code there was this:

```ruby
Capybara.server do |app, port|
  require 'rack/handler/thin'
  Rack::Handler::Thin.run(app, :Port => port)
end
```

Removing that line dropped the `:webkit` driver runs below the `:selenium` - which was what I expected given that it runs headless.

So I think the mystery of the mega slow tests is side-stepped for now. Not sure why running thin would tank it that hard. I'll keep looking into it. As for the issue, closing.

**Comment by tonywok** [comment] 2015-01-28 16:55
So I closed this after I deleted the above code, thinking that was the solution.

As it turns out, the reason that code was there was pretty well hidden. It's there to setup an app server for a mounted sinatra app in the test environment. The reason that is there is really specific to this application (mocking out streaming from external service).

I think the broader question is how does this ember-cli middleware act when there are requests being routed to a mounted rack application?

I think the mounted application would receive a new instance of the ember cli middleware, producing additional compilations. Does that make any sense?

**Comment by tonywok** [comment] 2015-01-28 21:05
So I just tried moving the mounted sinatra app to the `config.ru` to ensure that it wasn't picking up the `ember-cli-rails` middleware.

That just leaves me with thin. Have you used ember-cli-rails with thin per chance? I'll keep digging.

**Comment by rondale-sc** [comment] 2015-01-28 21:10
I know of a team using thin with ember-cli-rails.  They haven't run into any issues with their webdrivers though.  They are using capybara-webkit for their cukes.

**Comment by tonywok** [comment] 2015-01-28 21:40
@rondale-sc Welp, I'm curious if they are using thin as their capybara server, a la: 

```ruby
Capybara.server do |app, port|
  require 'rack/handler/thin'
  Rack::Handler::Thin.run(app, :Port => port)
end
```

If they are, and have no problem, it must be me :cry:

**Comment by rondale-sc** [comment] 2015-01-28 21:44
@tonywok Ah, I see.  Sorry, was distracted when I wrote that last comment.  I don't think they are using thin as their capybara server.

**Comment by rwz** [comment] 2015-02-09 02:01
@tonywok is there a way you could produce a stripped-down minimal all-businness-logic-removed version of your app recreating this behavior? I'm mostly interested in a way you test suite and your streaming sinatra app are set up.

I assume that the problem is that middleware is somehow losing its state between requests and has to recompile EmberCLI app multiple times instead of doing it once. No idea why it happens and hope that your example will help a lot debugging it.

**Comment by rondale-sc** [comment] 2015-02-13 18:26
@tonywok ping

**Comment by pedrocarrico** [comment] 2015-02-15 10:42
I'm running it with thin and poltergeist and currently don't see any performance drop.
Running with latest rails and ember-cli-rails and I can see that the EmberCLI app is indeed only being compiled once.
My EmberCLI app is in a directory in the root of the rails project.

This is how I do the initialisation:
```ruby
Capybara.default_driver = :poltergeist

Capybara.server do |app, port|
  require "rack/handler/thin"
  Rack::Handler::Thin.run(app, Port: port, signals: false)
end
```

**Comment by rondale-sc** [comment] 2015-02-25 01:43
Thanks @pedrocarrico!  

@tonywok I'm going to close this for now, if you are still having problems ping me here and we can reopen.

**Closed by rondale-sc** 2015-02-25 01:43 UTC
